CREATE TABLE IF NOT EXISTS `resources` (
  `autoid` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(10) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `key1` VARCHAR(50) NOT NULL,
  `key2` VARCHAR(50) NOT NULL,
  `key3` VARCHAR(50) NOT NULL,
  `key4` VARCHAR(50) NOT NULL,
  `xmlview` VARCHAR(10000) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT NOW(),
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`autoid`),
  UNIQUE `id` (`id`),
  KEY `key1` (`key1`),
  KEY `key2` (`key2`),
  KEY `key3` (`key3`),
  KEY `key4` (`key4`),
  KEY `created` (`created`),
  KEY `updated` (`updated`)
);

CREATE TABLE IF NOT EXISTS `links` (
  `autoid` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(10) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `source` VARCHAR(10) NOT NULL,
  `destination` VARCHAR(10) NOT NULL,
  `dt_start` VARCHAR(20) NOT NULL,
  `dt_end` VARCHAR(20) NOT NULL,
  `xmlview` VARCHAR(10000) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT NOW(),
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`autoid`),
  UNIQUE `id` (`id`),
  KEY `source` (`source`),
  KEY `destination` (`destination`),
  KEY `dt_start` (`dt_start`),
  KEY `dt_end` (`dt_end`),
  KEY `created` (`created`),
  KEY `updated` (`updated`)
);